/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSummaryRouteImport } from './routes/_app/summary'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRecurringRouteImport } from './routes/_app/recurring'
import { Route as AppLendingRouteImport } from './routes/_app/lending'
import { Route as AppIncomeRouteImport } from './routes/_app/income'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSummaryRoute = AppSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppLendingRoute = AppLendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/income': typeof AppIncomeRoute
  '/lending': typeof AppLendingRoute
  '/recurring': typeof AppRecurringRoute
  '/settings': typeof AppSettingsRoute
  '/summary': typeof AppSummaryRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/income': typeof AppIncomeRoute
  '/lending': typeof AppLendingRoute
  '/recurring': typeof AppRecurringRoute
  '/settings': typeof AppSettingsRoute
  '/summary': typeof AppSummaryRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/income': typeof AppIncomeRoute
  '/_app/lending': typeof AppLendingRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/summary': typeof AppSummaryRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/income'
    | '/lending'
    | '/recurring'
    | '/settings'
    | '/summary'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/income' | '/lending' | '/recurring' | '/settings' | '/summary' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/income'
    | '/_app/lending'
    | '/_app/recurring'
    | '/_app/settings'
    | '/_app/summary'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/summary': {
      id: '/_app/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AppSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lending': {
      id: '/_app/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof AppLendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIncomeRoute: typeof AppIncomeRoute
  AppLendingRoute: typeof AppLendingRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSummaryRoute: typeof AppSummaryRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIncomeRoute: AppIncomeRoute,
  AppLendingRoute: AppLendingRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSummaryRoute: AppSummaryRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
